# Generated by Django 2.0.5 on 2018-05-10 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('vote_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('ayes', models.IntegerField(blank=True, null=True)),
                ('nays', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
