# Generated by Django 2.0.5 on 2018-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20180510_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
